# Generated by Django 5.1.3 on 2024-12-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Default Address', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='default_state', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
